"""Convert CelesTrak SATCAT CSV to launch_dates.txt.

Output format (one sat per line):
    NORAD_ID | LAUNCH_DATE | OBJECT_NAME

- NORAD_ID     : catalog number, integer
- LAUNCH_DATE  : ISO YYYY-MM-DD (blank if SATCAT has no date yet)
- OBJECT_NAME  : NORAD name, for human readability only

Sorted by NORAD_ID. New satellites in the "SPACEMOBILE" name family appear
automatically the next time this workflow runs. Debris rows are filtered out.
"""
import csv
import sys
from pathlib import Path

src = Path(sys.argv[1])
dst = Path(sys.argv[2])

rows = []
with src.open(newline="", encoding="utf-8") as f:
    for r in csv.DictReader(f):
        try:
            norad = int(r["NORAD_CAT_ID"])
        except (KeyError, ValueError):
            continue
        if (r.get("OBJECT_TYPE") or "").strip() == "DEB":
            continue
        launch = (r.get("LAUNCH_DATE") or "").strip()
        name   = (r.get("OBJECT_NAME") or "").strip()
        rows.append((norad, launch, name))

rows.sort(key=lambda x: x[0])

lines = [
    "# Auto-generated by .github/workflows/update_launch_dates.yml",
    "# Source: CelesTrak SATCAT, NAME=SPACEMOBILE (debris filtered out)",
    "# Format: NORAD_ID | LAUNCH_DATE (YYYY-MM-DD) | OBJECT_NAME",
    "",
]
lines += [f"{n} | {d} | {name}" for n, d, name in rows]

dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {len(rows)} satellites to {dst}")
